### ISSUE TITLE
Implement search page

### ISSUE THREAD

**Issue by jerelmiller** [apollographql/spotify-showcase#12]
https://open.spotify.com/search

**Comment by alessbell** [comment]
Implemented the Search page and Artist search via https://github.com/apollographql/spotify-showcase/pull/87 so I'll close this out 🎉 

Linking some new issues for future Search page improvements:
- https://github.com/apollographql/spotify-showcase/issues/88
- https://github.com/apollographql/spotify-showcase/issues/89
